-- RM por ESTAGIO — PARTE 2 de 2: a IDENTIDADE NOVA.
--
-- ⚠️⚠️ ESTE ARQUIVO E O DEPLOY 1 DE DOIS. Ele CRIA o indice novo e NAO derruba o
-- antigo (`ux_rm_mun_anos_fontes`). Durante a troca de container, o codigo VELHO
-- (`ON CONFLICT (municipio_id, anos, fontes)`) e o NOVO
-- (`ON CONFLICT (municipio_id, anos, fontes, estagio)`) rodam ao MESMO TEMPO
-- contra este banco, e cada um precisa do SEU indice. Sem a coexistencia, o
-- container velho responde 42P10 ("there is no unique or exclusion constraint
-- matching the ON CONFLICT specification") em TODO POST /api/rm ate terminar de
-- sair do ar.
--
-- O DROP do antigo e `drop_rm_unique_anos_fontes.sql`, que so entra em
-- MIGRATION_FILES num PR POSTERIOR, depois deste estar em producao nos QUATRO
-- tenants. E a MESMA dança que `add_rm_fontes_indice.sql` +
-- `drop_rm_unique_anos.sql` ja fizeram — a diferenca e que agora ha um
-- precedente escrito, e ele diz que funciona.
--
-- Enquanto o indice antigo viver, o completo e o recorte por estagio do MESMO
-- periodo e das MESMAS consultas ainda nao coexistem (23505 no indice velho). E
-- temporario, e o router explica isso em 409 — ver o `except DBAPIError` de
-- rm.py::criar.
--
-- E UNIQUE INDEX (e nao constraint) pelo mesmo motivo dos anteriores:
-- `ON CONFLICT (colunas)` infere por lista de colunas e funciona;
-- `ON CONFLICT ON CONSTRAINT` nao.
--
-- ⚠️ Este CREATE NAO PODE falhar por dado duplicado, e e por isso que ele vem
-- ANTES do DROP e nao depois: enquanto `ux_rm_mun_anos_fontes` existe,
-- (municipio_id, anos, fontes) ja e unico, entao um indice que ACRESCENTA
-- `estagio` e forcosamente unico tambem. Na ordem invertida, um CREATE que
-- falhasse por duplicata seria classificado como "ja aplicada (skip)" pelo
-- runner (services/startup.py filtra a mensagem por substring "duplicate") e o
-- indice simplesmente NAO EXISTIRIA — com o ON CONFLICT novo estourando 42P10
-- em producao e o log dizendo que estava tudo certo.
CREATE UNIQUE INDEX IF NOT EXISTS ux_rm_mun_anos_fontes_estagio
    ON rm_relatorios (municipio_id, anos, fontes, estagio);
