from sqlalchemy import Column, Integer, String, Numeric, Date, DateTime, ForeignKey, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.sql import func
from database import Base


class ConvenioEstadual(Base):
    __tablename__ = "convenios_estadual"

    id = Column(Integer, primary_key=True, index=True)
    nr_sigcon = Column(String(50), index=True)
    nr_siafi = Column(String(50))
    municipio_id = Column(Integer, ForeignKey("municipios.id"), index=True)
    convenente_nome = Column(String(500))
    orgao_concedente = Column(String(500))
    objeto = Column(Text)
    objetivo = Column(Text)
    situacao = Column(String(200), index=True)
    tp_instrumento = Column(String(100))
    valor_concedente = Column(Numeric(18, 2))
    valor_emenda_parlamentar = Column(Numeric(18, 2))
    valor_contrapartida = Column(Numeric(18, 2))
    valor_total = Column(Numeric(18, 2))
    valor_repassado = Column(Numeric(18, 2))
    dt_publicacao = Column(Date)
    dt_vigencia_inicial = Column(Date)
    dt_vigencia_final = Column(Date)
    dt_vigencia_atual = Column(Date, index=True)
    ano = Column(Integer)
    etapa_sigcon = Column(String(200))
    etapa_sigcon_nr = Column(Integer)
    fonte = Column(String(50), default="SIGCON-MG")
    # Campos do Relatorio de Monitoramento (RM)
    banco = Column(String(100))
    agencia = Column(String(20))
    conta_corrente = Column(String(50))
    saldo_bancario = Column(Numeric(18, 2))
    dt_saldo = Column(Date)
    nr_sei = Column(String(100))
    dt_empenho = Column(Date)
    dt_desembolso = Column(Date)
    tipo_programa = Column(String(100))
    nr_indicacao = Column(String(50))
    resolucao = Column(String(100))
    # Campos do print SIGCON-MG (Convenio publicado view)
    nr_proposta = Column(String(50), index=True)
    nr_plano_trabalho = Column(String(50))
    qt_alteracoes = Column(Integer, default=0)
    dt_assinatura = Column(Date)
    raw_data = Column(JSONB)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
